version: '3.8'
services:
  app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - app.env
    networks:
      - pawnshop-network
    depends_on:
      - db
      - flyway
    restart: on-failure
    entrypoint: ["sh", "-c", "sleep 30 && java -jar app.jar"]

  flyway:
    image: flyway/flyway
    depends_on:
      - db
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    env_file:
      - app.env
    entrypoint: ["sh", "-c", "sleep 120 && flyway migrate"]
    restart: on-failure
    networks:
      - pawnshop-network

  db:
    container_name: postgres-db
    image: postgres
    env_file:
      - app.env
    ports:
      - "5432:5432"
    networks:
      - pawnshop-network
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    container_name: angular-app
    build:
      context: ../FE/UI
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - pawnshop-network
    depends_on:
      - app
    restart: unless-stopped

networks:
  pawnshop-network:
    driver: bridge

volumes:
  db-data:
